//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCakeMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public Nullable<int> shopId { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string phonenumber { get; set; }
        public string address { get; set; }
        public string email { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
