//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCakeMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> cakeId { get; set; }
    
        public virtual Cake Cake { get; set; }
        public virtual Orderr Orderr { get; set; }
    }
}
